apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-jobmanager
  namespace: flink-k8s-example
  labels:
    app: flink
spec:
  serviceName: flink-jobmanager
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      terminationGracePeriodSeconds: 20
      initContainers:
        - name: take-shared-dir-ownership
          image: alpine:3.6
          # Give `flink` group (id 9999) permissions to the shared mounted volume
          command:
            - chown
            - -R
            - 9999:9999
            - /flink-shared
          volumeMounts:
            - name: flink-shared-volume
              mountPath: /flink-shared
      containers:
        - name: jobmanager
          image: flink-k8s-example
          # remove this for real deployments
          imagePullPolicy: Never
          args: ["job-cluster"]
          ports:
            - containerPort: 6123
              name: rpc
            - containerPort: 6124
              name: blob
            - containerPort: 6125
              name: query
            - containerPort: 8081
              name: ui
            - containerPort: 50010
              name: ha
          livenessProbe:
            httpGet:
              path: /overview
              port: ui
            initialDelaySeconds: 90
            periodSeconds: 5
          volumeMounts:
            - name: flink-shared-volume
              mountPath: /flink-shared
            - name: flink-config-volume
              mountPath: /opt/flink/conf
          env:
            - name: FLINK_CONF_DIR
              value: /opt/flink/conf
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
              - key: log4j.properties
                path: log4j-console.properties
              - key: masters
                path: masters
        - name: flink-shared-volume
          persistentVolumeClaim:
            claimName: flink-shared-pvc