apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink-k8s-example
  labels:
    app: flink
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 6123
    - name: blob
      port: 6124
    - name: query
      port: 6125
    - name: ui
      port: 8081
    - name: ha
      port: 50010
  selector:
    app: flink
    component: jobmanager