apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
  namespace: flink-k8s-example
  labels:
    app: flink
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
  selector:
    app: flink
    component: jobmanager