kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: flink-sc
  labels:
    k8s-addon: storage-aws.addons.k8s.io
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-shared-pvc
  namespace: flink-k8s-example
spec:
  storageClassName: flink-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi